.\halite.exe -d "40 40" "python MyBot.py" "python RandomBot.py"
.\halite.exe -d "40 40" "python MyBot.py" "python RandomBot.py"
.\halite.exe -d "40 40" "python MyBot.py" "python RandomBot.py"
.\halite.exe -d "40 40" "python MyBot.py" "python RandomBot.py"
.\halite.exe -d "40 40" "python MyBot.py" "python RandomBot.py"
.\halite.exe -d "40 40" "python MyBot.py" "python RandomBot.py"